// Generated by Wrangler by running `wrangler types`

interface Env {
	ASSETS_KV_NAMESPACE: KVNamespace;
	ENVIRONMENT: "development";
	ASSETS_MANIFEST: "todo";
	CONFIG: {};
	VERSION_METADATA: WorkerVersionMetadata;
}
