// Generated by Wrangler by running `wrangler types`

interface Env {
	ASSETS_KV_NAMESPACE: KVNamespace;
	MANIFEST_KV_NAMESPACE: KVNamespace;
	ENVIRONMENT: "development";
	CONFIG: {"not_found_handling":"single-page-application"};
	VERSION_METADATA: WorkerVersionMetadata;
}
